{-# LANGUAGE JavaScriptFFI #-}
{-# OPTIONS_GHC -Wno-missing-signatures #-}

module Libsodium.GHCJS
  ( sodium_init
  ) where

import GHCJS.Types (JSVal, JSString)
import qualified Data.JSString as JSS
import Foreign.Emscripten (Mod(..), Arg(..), Ret(..), wrapModIO)

import qualified Libsodium.Functions as LF

--------------------------------------------------------------------------------

-- We use 'asTypeOf' to be sure we both render and support the type as the
-- "Libsodium.Functions" version intended.

sodium_init = sodium_init_ `asTypeOf` LF.sodium_init
sodium_init_ = do
  ea <- readyWait
  case ea of
    Left e   -> error e -- return -1? probably.
    Right () -> wrap >> LF.sodium_init

--------------------------------------------------------------------------------

-- | In GHCJS Wait for @libsodium@ finish to loading, reporting errors if any.
--
-- In GHC, does nothing and always return 'Right'.
readyWait :: IO (Either String ())
readyWait = do
  (ok, msg) <- js_libsodiumReadyWait
  pure $ case ok of
    True  -> Right ()
    False -> Left (JSS.unpack msg)

foreign import javascript interruptible "h$libsodium.onReady($c);"
  js_libsodiumReadyWait :: IO (Bool, JSString)

--------------------------------------------------------------------------------

foreign import javascript unsafe "$r = h$libsodium.emMod;" js_emMod :: JSVal

wrap :: IO ()
wrap = wrapModIO (Mod js_emMod)
  -- NUMERIC CONSTANTS
  [ ("crypto_aead_chacha20poly1305_abytes", RetVal, [])
  , ("crypto_aead_chacha20poly1305_ietf_abytes", RetVal, [])
  , ("crypto_aead_chacha20poly1305_ietf_keybytes", RetVal, [])
  , ("crypto_aead_chacha20poly1305_ietf_messagebytes_max", RetVal, [])
  , ("crypto_aead_chacha20poly1305_ietf_npubbytes", RetVal, [])
  , ("crypto_aead_chacha20poly1305_ietf_nsecbytes", RetVal, [])
  , ("crypto_aead_chacha20poly1305_keybytes", RetVal, [])
  , ("crypto_aead_chacha20poly1305_messagebytes_max", RetVal, [])
  , ("crypto_aead_chacha20poly1305_npubbytes", RetVal, [])
  , ("crypto_aead_chacha20poly1305_nsecbytes", RetVal, [])
  , ("crypto_aead_xchacha20poly1305_ietf_abytes", RetVal, [])
  , ("crypto_aead_xchacha20poly1305_ietf_keybytes", RetVal, [])
  , ("crypto_aead_xchacha20poly1305_ietf_messagebytes_max", RetVal, [])
  , ("crypto_aead_xchacha20poly1305_ietf_npubbytes", RetVal, [])
  , ("crypto_aead_xchacha20poly1305_ietf_nsecbytes", RetVal, [])
  , ("crypto_auth_bytes", RetVal, [])
  , ("crypto_auth_hmacsha256_bytes", RetVal, [])
  , ("crypto_auth_hmacsha256_keybytes", RetVal, [])
  , ("crypto_auth_hmacsha256_statebytes", RetVal, [])
  , ("crypto_auth_hmacsha512256_bytes", RetVal, [])
  , ("crypto_auth_hmacsha512256_keybytes", RetVal, [])
  , ("crypto_auth_hmacsha512256_statebytes", RetVal, [])
  , ("crypto_auth_hmacsha512_bytes", RetVal, [])
  , ("crypto_auth_hmacsha512_keybytes", RetVal, [])
  , ("crypto_auth_hmacsha512_statebytes", RetVal, [])
  , ("crypto_auth_keybytes", RetVal, [])
  , ("crypto_box_beforenmbytes", RetVal, [])
  , ("crypto_box_boxzerobytes", RetVal, [])
  , ("crypto_box_curve25519xchacha20poly1305_beforenmbytes", RetVal, [])
  , ("crypto_box_curve25519xchacha20poly1305_macbytes", RetVal, [])
  , ("crypto_box_curve25519xchacha20poly1305_messagebytes_max", RetVal, [])
  , ("crypto_box_curve25519xchacha20poly1305_noncebytes", RetVal, [])
  , ("crypto_box_curve25519xchacha20poly1305_publickeybytes", RetVal, [])
  , ("crypto_box_curve25519xchacha20poly1305_sealbytes", RetVal, [])
  , ("crypto_box_curve25519xchacha20poly1305_secretkeybytes", RetVal, [])
  , ("crypto_box_curve25519xchacha20poly1305_seedbytes", RetVal, [])
  , ("crypto_box_curve25519xsalsa20poly1305_beforenmbytes", RetVal, [])
  , ("crypto_box_curve25519xsalsa20poly1305_boxzerobytes", RetVal, [])
  , ("crypto_box_curve25519xsalsa20poly1305_macbytes", RetVal, [])
  , ("crypto_box_curve25519xsalsa20poly1305_messagebytes_max", RetVal, [])
  , ("crypto_box_curve25519xsalsa20poly1305_noncebytes", RetVal, [])
  , ("crypto_box_curve25519xsalsa20poly1305_publickeybytes", RetVal, [])
  , ("crypto_box_curve25519xsalsa20poly1305_secretkeybytes", RetVal, [])
  , ("crypto_box_curve25519xsalsa20poly1305_seedbytes", RetVal, [])
  , ("crypto_box_curve25519xsalsa20poly1305_zerobytes", RetVal, [])
  , ("crypto_box_macbytes", RetVal, [])
  , ("crypto_box_messagebytes_max", RetVal, [])
  , ("crypto_box_noncebytes", RetVal, [])
  , ("crypto_box_publickeybytes", RetVal, [])
  , ("crypto_box_sealbytes", RetVal, [])
  , ("crypto_box_secretkeybytes", RetVal, [])
  , ("crypto_box_seedbytes", RetVal, [])
  , ("crypto_box_zerobytes", RetVal, [])
  , ("crypto_core_ed25519_bytes", RetVal, [])
  , ("crypto_core_ed25519_hashbytes", RetVal, [])
  , ("crypto_core_ed25519_nonreducedscalarbytes", RetVal, [])
  , ("crypto_core_ed25519_scalarbytes", RetVal, [])
  , ("crypto_core_ed25519_uniformbytes", RetVal, [])
  , ("crypto_core_hchacha20_constbytes", RetVal, [])
  , ("crypto_core_hchacha20_inputbytes", RetVal, [])
  , ("crypto_core_hchacha20_keybytes", RetVal, [])
  , ("crypto_core_hchacha20_outputbytes", RetVal, [])
  , ("crypto_core_hsalsa20_constbytes", RetVal, [])
  , ("crypto_core_hsalsa20_inputbytes", RetVal, [])
  , ("crypto_core_hsalsa20_keybytes", RetVal, [])
  , ("crypto_core_hsalsa20_outputbytes", RetVal, [])
  , ("crypto_core_ristretto255_bytes", RetVal, [])
  , ("crypto_core_ristretto255_hashbytes", RetVal, [])
  , ("crypto_core_ristretto255_nonreducedscalarbytes", RetVal, [])
  , ("crypto_core_ristretto255_scalarbytes", RetVal, [])
  , ("crypto_core_salsa2012_constbytes", RetVal, [])
  , ("crypto_core_salsa2012_inputbytes", RetVal, [])
  , ("crypto_core_salsa2012_keybytes", RetVal, [])
  , ("crypto_core_salsa2012_outputbytes", RetVal, [])
  , ("crypto_core_salsa208_constbytes", RetVal, [])
  , ("crypto_core_salsa208_inputbytes", RetVal, [])
  , ("crypto_core_salsa208_keybytes", RetVal, [])
  , ("crypto_core_salsa208_outputbytes", RetVal, [])
  , ("crypto_core_salsa20_constbytes", RetVal, [])
  , ("crypto_core_salsa20_inputbytes", RetVal, [])
  , ("crypto_core_salsa20_keybytes", RetVal, [])
  , ("crypto_core_salsa20_outputbytes", RetVal, [])
  , ("crypto_generichash_blake2b_bytes", RetVal, [])
  , ("crypto_generichash_blake2b_bytes_max", RetVal, [])
  , ("crypto_generichash_blake2b_bytes_min", RetVal, [])
  , ("crypto_generichash_blake2b_keybytes", RetVal, [])
  , ("crypto_generichash_blake2b_keybytes_max", RetVal, [])
  , ("crypto_generichash_blake2b_keybytes_min", RetVal, [])
  , ("crypto_generichash_blake2b_personalbytes", RetVal, [])
  , ("crypto_generichash_blake2b_saltbytes", RetVal, [])
  , ("crypto_generichash_blake2b_statebytes", RetVal, [])
  , ("crypto_generichash_bytes", RetVal, [])
  , ("crypto_generichash_bytes_max", RetVal, [])
  , ("crypto_generichash_bytes_min", RetVal, [])
  , ("crypto_generichash_keybytes", RetVal, [])
  , ("crypto_generichash_keybytes_max", RetVal, [])
  , ("crypto_generichash_keybytes_min", RetVal, [])
  , ("crypto_generichash_statebytes", RetVal, [])
  , ("crypto_hash_bytes", RetVal, [])
  , ("crypto_hash_sha256_bytes", RetVal, [])
  , ("crypto_hash_sha256_statebytes", RetVal, [])
  , ("crypto_hash_sha512_bytes", RetVal, [])
  , ("crypto_hash_sha512_statebytes", RetVal, [])
  , ("crypto_kdf_blake2b_bytes_max", RetVal, [])
  , ("crypto_kdf_blake2b_bytes_min", RetVal, [])
  , ("crypto_kdf_blake2b_contextbytes", RetVal, [])
  , ("crypto_kdf_blake2b_keybytes", RetVal, [])
  , ("crypto_kdf_bytes_max", RetVal, [])
  , ("crypto_kdf_bytes_min", RetVal, [])
  , ("crypto_kdf_contextbytes", RetVal, [])
  , ("crypto_kdf_keybytes", RetVal, [])
  , ("crypto_kx_publickeybytes", RetVal, [])
  , ("crypto_kx_secretkeybytes", RetVal, [])
  , ("crypto_kx_seedbytes", RetVal, [])
  , ("crypto_kx_sessionkeybytes", RetVal, [])
  , ("crypto_onetimeauth_bytes", RetVal, [])
  , ("crypto_onetimeauth_keybytes", RetVal, [])
  , ("crypto_onetimeauth_poly1305_bytes", RetVal, [])
  , ("crypto_onetimeauth_poly1305_keybytes", RetVal, [])
  , ("crypto_onetimeauth_poly1305_statebytes", RetVal, [])
  , ("crypto_onetimeauth_statebytes", RetVal, [])
  , ("crypto_pwhash_alg_argon2i13", RetVal, [])
  , ("crypto_pwhash_alg_argon2id13", RetVal, [])
  , ("crypto_pwhash_alg_default", RetVal, [])
  , ("crypto_pwhash_argon2i_alg_argon2i13", RetVal, [])
  , ("crypto_pwhash_argon2i_bytes_max", RetVal, [])
  , ("crypto_pwhash_argon2i_bytes_min", RetVal, [])
  , ("crypto_pwhash_argon2id_alg_argon2id13", RetVal, [])
  , ("crypto_pwhash_argon2id_bytes_max", RetVal, [])
  , ("crypto_pwhash_argon2id_bytes_min", RetVal, [])
  , ("crypto_pwhash_argon2id_memlimit_interactive", RetVal, [])
  , ("crypto_pwhash_argon2id_memlimit_max", RetVal, [])
  , ("crypto_pwhash_argon2id_memlimit_min", RetVal, [])
  , ("crypto_pwhash_argon2id_memlimit_moderate", RetVal, [])
  , ("crypto_pwhash_argon2id_memlimit_sensitive", RetVal, [])
  , ("crypto_pwhash_argon2id_opslimit_interactive", RetVal, [])
  , ("crypto_pwhash_argon2id_opslimit_max", RetVal, [])
  , ("crypto_pwhash_argon2id_opslimit_min", RetVal, [])
  , ("crypto_pwhash_argon2id_opslimit_moderate", RetVal, [])
  , ("crypto_pwhash_argon2id_opslimit_sensitive", RetVal, [])
  , ("crypto_pwhash_argon2id_passwd_max", RetVal, [])
  , ("crypto_pwhash_argon2id_passwd_min", RetVal, [])
  , ("crypto_pwhash_argon2id_saltbytes", RetVal, [])
  , ("crypto_pwhash_argon2id_strbytes", RetVal, [])
  , ("crypto_pwhash_argon2i_memlimit_interactive", RetVal, [])
  , ("crypto_pwhash_argon2i_memlimit_max", RetVal, [])
  , ("crypto_pwhash_argon2i_memlimit_min", RetVal, [])
  , ("crypto_pwhash_argon2i_memlimit_moderate", RetVal, [])
  , ("crypto_pwhash_argon2i_memlimit_sensitive", RetVal, [])
  , ("crypto_pwhash_argon2i_opslimit_interactive", RetVal, [])
  , ("crypto_pwhash_argon2i_opslimit_max", RetVal, [])
  , ("crypto_pwhash_argon2i_opslimit_min", RetVal, [])
  , ("crypto_pwhash_argon2i_opslimit_moderate", RetVal, [])
  , ("crypto_pwhash_argon2i_opslimit_sensitive", RetVal, [])
  , ("crypto_pwhash_argon2i_passwd_max", RetVal, [])
  , ("crypto_pwhash_argon2i_passwd_min", RetVal, [])
  , ("crypto_pwhash_argon2i_saltbytes", RetVal, [])
  , ("crypto_pwhash_argon2i_strbytes", RetVal, [])
  , ("crypto_pwhash_bytes_max", RetVal, [])
  , ("crypto_pwhash_bytes_min", RetVal, [])
  , ("crypto_pwhash_memlimit_interactive", RetVal, [])
  , ("crypto_pwhash_memlimit_max", RetVal, [])
  , ("crypto_pwhash_memlimit_min", RetVal, [])
  , ("crypto_pwhash_memlimit_moderate", RetVal, [])
  , ("crypto_pwhash_memlimit_sensitive", RetVal, [])
  , ("crypto_pwhash_opslimit_interactive", RetVal, [])
  , ("crypto_pwhash_opslimit_max", RetVal, [])
  , ("crypto_pwhash_opslimit_min", RetVal, [])
  , ("crypto_pwhash_opslimit_moderate", RetVal, [])
  , ("crypto_pwhash_opslimit_sensitive", RetVal, [])
  , ("crypto_pwhash_passwd_max", RetVal, [])
  , ("crypto_pwhash_passwd_min", RetVal, [])
  , ("crypto_pwhash_saltbytes", RetVal, [])
  , ("crypto_pwhash_scryptsalsa208sha256_bytes_max", RetVal, [])
  , ("crypto_pwhash_scryptsalsa208sha256_bytes_min", RetVal, [])
  , ("crypto_pwhash_scryptsalsa208sha256_memlimit_interactive", RetVal, [])
  , ("crypto_pwhash_scryptsalsa208sha256_memlimit_max", RetVal, [])
  , ("crypto_pwhash_scryptsalsa208sha256_memlimit_min", RetVal, [])
  , ("crypto_pwhash_scryptsalsa208sha256_memlimit_sensitive", RetVal, [])
  , ("crypto_pwhash_scryptsalsa208sha256_opslimit_interactive", RetVal, [])
  , ("crypto_pwhash_scryptsalsa208sha256_opslimit_max", RetVal, [])
  , ("crypto_pwhash_scryptsalsa208sha256_opslimit_min", RetVal, [])
  , ("crypto_pwhash_scryptsalsa208sha256_opslimit_sensitive", RetVal, [])
  , ("crypto_pwhash_scryptsalsa208sha256_passwd_max", RetVal, [])
  , ("crypto_pwhash_scryptsalsa208sha256_passwd_min", RetVal, [])
  , ("crypto_pwhash_scryptsalsa208sha256_saltbytes", RetVal, [])
  , ("crypto_pwhash_scryptsalsa208sha256_strbytes", RetVal, [])
  , ("crypto_pwhash_strbytes", RetVal, [])
  , ("crypto_scalarmult_bytes", RetVal, [])
  , ("crypto_scalarmult_curve25519_bytes", RetVal, [])
  , ("crypto_scalarmult_curve25519_scalarbytes", RetVal, [])
  , ("crypto_scalarmult_ed25519_bytes", RetVal, [])
  , ("crypto_scalarmult_ed25519_scalarbytes", RetVal, [])
  , ("crypto_scalarmult_ristretto255_bytes", RetVal, [])
  , ("crypto_scalarmult_ristretto255_scalarbytes", RetVal, [])
  , ("crypto_scalarmult_scalarbytes", RetVal, [])
  , ("crypto_secretbox_boxzerobytes", RetVal, [])
  , ("crypto_secretbox_keybytes", RetVal, [])
  , ("crypto_secretbox_macbytes", RetVal, [])
  , ("crypto_secretbox_messagebytes_max", RetVal, [])
  , ("crypto_secretbox_noncebytes", RetVal, [])
  , ("crypto_secretbox_xchacha20poly1305_keybytes", RetVal, [])
  , ("crypto_secretbox_xchacha20poly1305_macbytes", RetVal, [])
  , ("crypto_secretbox_xchacha20poly1305_messagebytes_max", RetVal, [])
  , ("crypto_secretbox_xchacha20poly1305_noncebytes", RetVal, [])
  , ("crypto_secretbox_xsalsa20poly1305_boxzerobytes", RetVal, [])
  , ("crypto_secretbox_xsalsa20poly1305_keybytes", RetVal, [])
  , ("crypto_secretbox_xsalsa20poly1305_macbytes", RetVal, [])
  , ("crypto_secretbox_xsalsa20poly1305_messagebytes_max", RetVal, [])
  , ("crypto_secretbox_xsalsa20poly1305_noncebytes", RetVal, [])
  , ("crypto_secretbox_xsalsa20poly1305_zerobytes", RetVal, [])
  , ("crypto_secretbox_zerobytes", RetVal, [])
  , ("crypto_secretstream_xchacha20poly1305_abytes", RetVal, [])
  , ("crypto_secretstream_xchacha20poly1305_headerbytes", RetVal, [])
  , ("crypto_secretstream_xchacha20poly1305_keybytes", RetVal, [])
  , ("crypto_secretstream_xchacha20poly1305_messagebytes_max", RetVal, [])
  , ("crypto_secretstream_xchacha20poly1305_statebytes", RetVal, [])
  , ("crypto_secretstream_xchacha20poly1305_tag_final", RetVal, [])
  , ("crypto_secretstream_xchacha20poly1305_tag_message", RetVal, [])
  , ("crypto_secretstream_xchacha20poly1305_tag_push", RetVal, [])
  , ("crypto_secretstream_xchacha20poly1305_tag_rekey", RetVal, [])
  , ("crypto_shorthash_bytes", RetVal, [])
  , ("crypto_shorthash_keybytes", RetVal, [])
  , ("crypto_shorthash_siphash24_bytes", RetVal, [])
  , ("crypto_shorthash_siphash24_keybytes", RetVal, [])
  , ("crypto_shorthash_siphashx24_bytes", RetVal, [])
  , ("crypto_shorthash_siphashx24_keybytes", RetVal, [])
  , ("crypto_sign_bytes", RetVal, [])
  , ("crypto_sign_ed25519_bytes", RetVal, [])
  , ("crypto_sign_ed25519_messagebytes_max", RetVal, [])
  , ("crypto_sign_ed25519ph_statebytes", RetVal, [])
  , ("crypto_sign_ed25519_publickeybytes", RetVal, [])
  , ("crypto_sign_ed25519_secretkeybytes", RetVal, [])
  , ("crypto_sign_ed25519_seedbytes", RetVal, [])
  , ("crypto_sign_messagebytes_max", RetVal, [])
  , ("crypto_sign_publickeybytes", RetVal, [])
  , ("crypto_sign_secretkeybytes", RetVal, [])
  , ("crypto_sign_seedbytes", RetVal, [])
  , ("crypto_sign_statebytes", RetVal, [])
  , ("crypto_stream_chacha20_ietf_keybytes", RetVal, [])
  , ("crypto_stream_chacha20_ietf_messagebytes_max", RetVal, [])
  , ("crypto_stream_chacha20_ietf_noncebytes", RetVal, [])
  , ("crypto_stream_chacha20_keybytes", RetVal, [])
  , ("crypto_stream_chacha20_messagebytes_max", RetVal, [])
  , ("crypto_stream_chacha20_noncebytes", RetVal, [])
  , ("crypto_stream_keybytes", RetVal, [])
  , ("crypto_stream_messagebytes_max", RetVal, [])
  , ("crypto_stream_noncebytes", RetVal, [])
  , ("crypto_stream_salsa2012_keybytes", RetVal, [])
  , ("crypto_stream_salsa2012_messagebytes_max", RetVal, [])
  , ("crypto_stream_salsa2012_noncebytes", RetVal, [])
  , ("crypto_stream_salsa208_keybytes", RetVal, [])
  , ("crypto_stream_salsa208_messagebytes_max", RetVal, [])
  , ("crypto_stream_salsa208_noncebytes", RetVal, [])
  , ("crypto_stream_salsa20_keybytes", RetVal, [])
  , ("crypto_stream_salsa20_messagebytes_max", RetVal, [])
  , ("crypto_stream_salsa20_noncebytes", RetVal, [])
  , ("crypto_stream_xchacha20_keybytes", RetVal, [])
  , ("crypto_stream_xchacha20_messagebytes_max", RetVal, [])
  , ("crypto_stream_xchacha20_noncebytes", RetVal, [])
  , ("crypto_stream_xsalsa20_keybytes", RetVal, [])
  , ("crypto_stream_xsalsa20_messagebytes_max", RetVal, [])
  , ("crypto_stream_xsalsa20_noncebytes", RetVal, [])
  , ("crypto_verify_16_bytes", RetVal, [])
  , ("crypto_verify_32_bytes", RetVal, [])
  , ("crypto_verify_64_bytes", RetVal, [])
  , ("randombytes_seedbytes", RetVal, [])
  , ("sodium_library_minimal", RetVal, [])
  , ("sodium_library_version_major", RetVal, [])
  , ("sodium_library_version_minor", RetVal, [])

  -- STRING CONSTANTS
  , ("sodium_version_string", RetStr, [])
  , ("crypto_auth_primitive", RetStr, [])
  , ("crypto_box_primitive", RetStr, [])
  , ("crypto_generichash_primitive", RetStr, [])
  , ("crypto_hash_primitive", RetStr, [])
  , ("crypto_kdf_primitive", RetStr, [])
  , ("crypto_kx_primitive", RetStr, [])
  , ("crypto_onetimeauth_primitive", RetStr, [])
  , ("crypto_pwhash_argon2id_strprefix", RetStr, [])
  , ("crypto_pwhash_argon2i_strprefix", RetStr, [])
  , ("crypto_pwhash_primitive", RetStr, [])
  , ("crypto_pwhash_scryptsalsa208sha256_strprefix", RetStr, [])
  , ("crypto_pwhash_strprefix", RetStr, [])
  , ("crypto_scalarmult_primitive", RetStr, [])
  , ("crypto_secretbox_primitive", RetStr, [])
  , ("crypto_shorthash_primitive", RetStr, [])
  , ("crypto_sign_primitive", RetStr, [])
  , ("crypto_stream_primitive", RetStr, [])
  , ("sodium_version_string", RetStr, [])

  -- FUNCTIONS (most pointers are curerntly passed in as 'ArgBufRWz' which
  -- copies into Emscripten heap and back, and then wipes the Emscripten memory,
  -- but really they should be changed to the more efficient variants that only
  -- do wthat they need to do (e.g. 'ArgBufW').
  , ("crypto_aead_chacha20poly1305_decrypt_detached", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_aead_chacha20poly1305_decrypt", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_aead_chacha20poly1305_encrypt_detached", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_aead_chacha20poly1305_encrypt", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_aead_chacha20poly1305_keygen", RetVoid, [ArgBufRWz])

  , ("crypto_aead_chacha20poly1305_ietf_decrypt_detached", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_aead_chacha20poly1305_ietf_decrypt", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_aead_chacha20poly1305_ietf_encrypt_detached", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_aead_chacha20poly1305_ietf_encrypt", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_aead_chacha20poly1305_ietf_keygen", RetVoid, [ArgBufRWz])

  , ("crypto_aead_xchacha20poly1305_ietf_decrypt_detached", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_aead_xchacha20poly1305_ietf_decrypt", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_aead_xchacha20poly1305_ietf_encrypt_detached", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_aead_xchacha20poly1305_ietf_encrypt", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_aead_xchacha20poly1305_ietf_keygen", RetVoid, [ArgBufRWz])

  , ("crypto_auth_hmacsha256_final", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_auth_hmacsha256_init", RetVal, [ArgBufRWz, ArgBufRWz, ArgVal])
  , ("crypto_auth_hmacsha256_keygen", RetVoid, [ArgBufRWz])
  , ("crypto_auth_hmacsha256", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])
  , ("crypto_auth_hmacsha256_update", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64])
  , ("crypto_auth_hmacsha256_verify", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])

  , ("crypto_auth_hmacsha512256_final", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_auth_hmacsha512256_init", RetVal, [ArgBufRWz, ArgBufRWz, ArgVal])
  , ("crypto_auth_hmacsha512256_keygen", RetVoid, [ArgBufRWz])
  , ("crypto_auth_hmacsha512256", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])
  , ("crypto_auth_hmacsha512256_update", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64])
  , ("crypto_auth_hmacsha512256_verify", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])

  , ("crypto_auth_hmacsha512_final", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_auth_hmacsha512_init", RetVal, [ArgBufRWz, ArgBufRWz, ArgVal])
  , ("crypto_auth_hmacsha512_keygen", RetVoid, [ArgBufRWz])
  , ("crypto_auth_hmacsha512", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])
  , ("crypto_auth_hmacsha512_update", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64])
  , ("crypto_auth_hmacsha512_verify", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])

  , ("crypto_auth_keygen", RetVoid, [ArgBufRWz])
  , ("crypto_auth", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])
  , ("crypto_auth_verify", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])

  , ("crypto_box_detached_afternm", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_detached", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_easy_afternm", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_easy", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_keypair", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_box_open_afternm", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_open_detached_afternm", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_open_detached", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_open_easy_afternm", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_open_easy", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_open", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_box", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_seal_open", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_seal", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])
  , ("crypto_box_seed_keypair", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_afternm", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_beforenm", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])

  , ("crypto_box_curve25519xchacha20poly1305_beforenm", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_curve25519xchacha20poly1305_detached_afternm", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_curve25519xchacha20poly1305_detached", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_curve25519xchacha20poly1305_easy_afternm", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_curve25519xchacha20poly1305_easy", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_curve25519xchacha20poly1305_keypair", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_box_curve25519xchacha20poly1305_open_detached_afternm", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_curve25519xchacha20poly1305_open_detached", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_curve25519xchacha20poly1305_open_easy_afternm", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_curve25519xchacha20poly1305_open_easy", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_curve25519xchacha20poly1305_seal_open", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_curve25519xchacha20poly1305_seal", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])
  , ("crypto_box_curve25519xchacha20poly1305_seed_keypair", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_curve25519xsalsa20poly1305_afternm", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_curve25519xsalsa20poly1305_beforenm", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_curve25519xsalsa20poly1305_keypair", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_box_curve25519xsalsa20poly1305_open_afternm", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_curve25519xsalsa20poly1305_open", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_curve25519xsalsa20poly1305", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_box_curve25519xsalsa20poly1305_seed_keypair", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])

  , ("crypto_core_ed25519_add", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_core_ed25519_from_hash", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_core_ed25519_from_uniform", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_core_ed25519_is_valid_point", RetVal, [ArgBufRWz])
  , ("crypto_core_ed25519_random", RetVoid, [ArgBufRWz])
  , ("crypto_core_ed25519_scalar_add", RetVoid, [ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_core_ed25519_scalar_complement", RetVoid, [ArgBufRWz, ArgBufRWz])
  , ("crypto_core_ed25519_scalar_invert", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_core_ed25519_scalar_mul", RetVoid, [ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_core_ed25519_scalar_negate", RetVoid, [ArgBufRWz, ArgBufRWz])
  , ("crypto_core_ed25519_scalar_random", RetVoid, [ArgBufRWz])
  , ("crypto_core_ed25519_scalar_reduce", RetVoid, [ArgBufRWz, ArgBufRWz])
  , ("crypto_core_ed25519_scalar_sub", RetVoid, [ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_core_ed25519_sub", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])

  , ("crypto_core_hchacha20", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgBufRWz])

  , ("crypto_core_hsalsa20", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgBufRWz])

  , ("crypto_core_ristretto255_add", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_core_ristretto255_from_hash", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_core_ristretto255_is_valid_point", RetVal, [ArgBufRWz])
  , ("crypto_core_ristretto255_random", RetVoid, [ArgBufRWz])
  , ("crypto_core_ristretto255_scalar_add", RetVoid, [ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_core_ristretto255_scalar_complement", RetVoid, [ArgBufRWz, ArgBufRWz])
  , ("crypto_core_ristretto255_scalar_invert", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_core_ristretto255_scalar_mul", RetVoid, [ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_core_ristretto255_scalar_negate", RetVoid, [ArgBufRWz, ArgBufRWz])
  , ("crypto_core_ristretto255_scalar_random", RetVoid, [ArgBufRWz])
  , ("crypto_core_ristretto255_scalar_reduce", RetVoid, [ArgBufRWz, ArgBufRWz])
  , ("crypto_core_ristretto255_scalar_sub", RetVoid, [ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_core_ristretto255_sub", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])

  , ("crypto_core_salsa2012", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_core_salsa208", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_core_salsa20", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgBufRWz])

  , ("crypto_generichash_blake2b_final", RetVal, [ArgBufRWz, ArgBufRWz, ArgVal])
  , ("crypto_generichash_blake2b_init", RetVal, [ArgBufRWz, ArgBufRWz, ArgVal, ArgVal])
  , ("crypto_generichash_blake2b_init_salt_personal", RetVal, [ArgBufRWz, ArgBufRWz, ArgVal, ArgVal, ArgBufRWz, ArgBufRWz])
  , ("crypto_generichash_blake2b_keygen", RetVoid, [ArgBufRWz])
  , ("crypto_generichash_blake2b", RetVal, [ArgBufRWz, ArgVal, ArgBufRWz, ArgI64, ArgBufRWz, ArgVal])
  , ("crypto_generichash_blake2b_salt_personal", RetVal, [ArgBufRWz, ArgVal, ArgBufRWz, ArgI64, ArgBufRWz, ArgVal, ArgBufRWz, ArgBufRWz])
  , ("crypto_generichash_blake2b_update", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64])

  , ("crypto_generichash_final", RetVal, [ArgBufRWz, ArgBufRWz, ArgVal])
  , ("crypto_generichash_init", RetVal, [ArgBufRWz, ArgBufRWz, ArgVal, ArgVal])
  , ("crypto_generichash_keygen", RetVoid, [ArgBufRWz])
  , ("crypto_generichash", RetVal, [ArgBufRWz, ArgVal, ArgBufRWz, ArgI64, ArgBufRWz, ArgVal])
  , ("crypto_generichash_update", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64])

  , ("crypto_hash", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64])

  , ("crypto_hash_sha256_final", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_hash_sha256_init", RetVal, [ArgBufRWz])
  , ("crypto_hash_sha256", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64])
  , ("crypto_hash_sha256_update", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64])

  , ("crypto_hash_sha512_final", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_hash_sha512_init", RetVal, [ArgBufRWz])
  , ("crypto_hash_sha512", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64])
  , ("crypto_hash_sha512_update", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64])

  , ("crypto_kdf_blake2b_derive_from_key", RetVal, [ArgBufRWz, ArgVal, ArgI64, ArgBufRWz, ArgBufRWz])

  , ("crypto_kdf_derive_from_key", RetVal, [ArgBufRWz, ArgVal, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_kdf_keygen", RetVoid, [ArgBufRWz])

  , ("crypto_kx_client_session_keys", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_kx_keypair", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_kx_seed_keypair", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_kx_server_session_keys", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgBufRWz])

  , ("crypto_onetimeauth_final", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_onetimeauth_init", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_onetimeauth_keygen", RetVoid, [ArgBufRWz])

  , ("crypto_onetimeauth_poly1305_final", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_onetimeauth_poly1305_init", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_onetimeauth_poly1305_keygen", RetVoid, [ArgBufRWz])
  , ("crypto_onetimeauth_poly1305", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])
  , ("crypto_onetimeauth_poly1305_update", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64])
  , ("crypto_onetimeauth_poly1305_verify", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])

  , ("crypto_onetimeauth", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])
  , ("crypto_onetimeauth_update", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64])
  , ("crypto_onetimeauth_verify", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])

  , ("crypto_pwhash_argon2id", RetVal, [ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgVal, ArgVal])
  , ("crypto_pwhash_argon2id_str_needs_rehash", RetVal, [ArgBufRWz, ArgI64, ArgVal])
  , ("crypto_pwhash_argon2id_str", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgI64, ArgVal])
  , ("crypto_pwhash_argon2id_str_verify", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64])
  , ("crypto_pwhash_argon2i", RetVal, [ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgVal, ArgVal])
  , ("crypto_pwhash_argon2i_str_needs_rehash", RetVal, [ArgBufRWz, ArgI64, ArgVal])
  , ("crypto_pwhash_argon2i_str", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgI64, ArgVal])
  , ("crypto_pwhash_argon2i_str_verify", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64])

  , ("crypto_pwhash", RetVal, [ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgVal, ArgVal])
  , ("crypto_pwhash_str_alg", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgI64, ArgVal, ArgVal])
  , ("crypto_pwhash_str_needs_rehash", RetVal, [ArgBufRWz, ArgI64, ArgVal])
  , ("crypto_pwhash_str", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgI64, ArgVal])
  , ("crypto_pwhash_str_verify", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64])

  , ("crypto_pwhash_scryptsalsa208sha256_ll", RetVal, [ArgBufRWz, ArgVal, ArgBufRWz, ArgVal, ArgI64, ArgVal, ArgVal, ArgBufRWz, ArgVal])
  , ("crypto_pwhash_scryptsalsa208sha256", RetVal, [ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgVal])
  , ("crypto_pwhash_scryptsalsa208sha256_str_needs_rehash", RetVal, [ArgBufRWz, ArgI64, ArgVal])
  , ("crypto_pwhash_scryptsalsa208sha256_str", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgI64, ArgVal])
  , ("crypto_pwhash_scryptsalsa208sha256_str_verify", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64])

  , ("crypto_scalarmult_curve25519_base", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_scalarmult_curve25519", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_scalarmult_ed25519_base_noclamp", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_scalarmult_ed25519_base", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_scalarmult_ed25519_noclamp", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_scalarmult_ed25519", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])

  , ("crypto_scalarmult_base", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_scalarmult", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])

  , ("crypto_scalarmult_ristretto255_base", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_scalarmult_ristretto255", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])

  , ("crypto_secretbox_detached", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_secretbox_easy", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_secretbox_keygen", RetVoid, [ArgBufRWz])
  , ("crypto_secretbox_open_detached", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_secretbox_open_easy", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_secretbox_open", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_secretbox", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])

  , ("crypto_secretbox_xchacha20poly1305_detached", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_secretbox_xchacha20poly1305_easy", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_secretbox_xchacha20poly1305_open_detached", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_secretbox_xchacha20poly1305_open_easy", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])

  , ("crypto_secretbox_xsalsa20poly1305_keygen", RetVoid, [ArgBufRWz])
  , ("crypto_secretbox_xsalsa20poly1305_open", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_secretbox_xsalsa20poly1305", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])

  , ("crypto_secretstream_xchacha20poly1305_init_pull", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_secretstream_xchacha20poly1305_init_push", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_secretstream_xchacha20poly1305_keygen", RetVoid, [ArgBufRWz])
  , ("crypto_secretstream_xchacha20poly1305_pull", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgI64])
  , ("crypto_secretstream_xchacha20poly1305_push", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgVal])
  , ("crypto_secretstream_xchacha20poly1305_rekey", RetVoid, [ArgBufRWz])

  , ("crypto_shorthash_keygen", RetVoid, [ArgBufRWz])
  , ("crypto_shorthash", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])
  , ("crypto_shorthash_siphash24", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])
  , ("crypto_shorthash_siphashx24", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])

  , ("crypto_sign_ed25519_detached", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])
  , ("crypto_sign_ed25519_keypair", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_sign_ed25519_open", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])
  , ("crypto_sign_ed25519_pk_to_curve25519", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_sign_ed25519", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])
  , ("crypto_sign_ed25519_seed_keypair", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_sign_ed25519_sk_to_curve25519", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_sign_ed25519_sk_to_pk", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_sign_ed25519_sk_to_seed", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_sign_ed25519_verify_detached", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])

  , ("crypto_sign_ed25519ph_final_create", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_sign_ed25519ph_final_verify", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_sign_ed25519ph_init", RetVal, [ArgBufRWz])
  , ("crypto_sign_ed25519ph_update", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64])

  , ("crypto_sign_detached", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])
  , ("crypto_sign_final_create", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_sign_final_verify", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_sign_init", RetVal, [ArgBufRWz])
  , ("crypto_sign_keypair", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_sign_open", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])
  , ("crypto_sign", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])
  , ("crypto_sign_seed_keypair", RetVal, [ArgBufRWz, ArgBufRWz, ArgBufRWz])
  , ("crypto_sign_update", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64])
  , ("crypto_sign_verify_detached", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz])

  , ("crypto_stream_chacha20_ietf_keygen", RetVoid, [ArgBufRWz])
  , ("crypto_stream_chacha20_ietf", RetVal, [ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_stream_chacha20_ietf_xor_ic", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgVal, ArgBufRWz])
  , ("crypto_stream_chacha20_ietf_xor", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_stream_chacha20_keygen", RetVoid, [ArgBufRWz])
  , ("crypto_stream_chacha20", RetVal, [ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_stream_chacha20_xor_ic", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgBufRWz])
  , ("crypto_stream_chacha20_xor", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])

  , ("crypto_stream_keygen", RetVoid, [ArgBufRWz])
  , ("crypto_stream_xor", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_stream", RetVal, [ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])

  , ("crypto_stream_salsa2012_keygen", RetVoid, [ArgBufRWz])
  , ("crypto_stream_salsa2012", RetVal, [ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_stream_salsa2012_xor", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_stream_salsa208_keygen", RetVoid, [ArgBufRWz])
  , ("crypto_stream_salsa208", RetVal, [ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_stream_salsa208_xor", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_stream_salsa20_keygen", RetVoid, [ArgBufRWz])
  , ("crypto_stream_salsa20", RetVal, [ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_stream_salsa20_xor_ic", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgBufRWz])
  , ("crypto_stream_salsa20_xor", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])

  , ("crypto_stream_xchacha20_keygen", RetVoid, [ArgBufRWz])
  , ("crypto_stream_xchacha20", RetVal, [ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_stream_xchacha20_xor_ic", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgBufRWz])
  , ("crypto_stream_xchacha20_xor", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])

  , ("crypto_stream_xsalsa20_keygen", RetVoid, [ArgBufRWz])
  , ("crypto_stream_xsalsa20", RetVal, [ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])
  , ("crypto_stream_xsalsa20_xor_ic", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgI64, ArgBufRWz])
  , ("crypto_stream_xsalsa20_xor", RetVal, [ArgBufRWz, ArgBufRWz, ArgI64, ArgBufRWz, ArgBufRWz])

  , ("crypto_verify_16", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_verify_32", RetVal, [ArgBufRWz, ArgBufRWz])
  , ("crypto_verify_64", RetVal, [ArgBufRWz, ArgBufRWz])

  , ("randombytes_buf", RetVoid, [ArgBufRWz, ArgVal])
  , ("randombytes_buf_deterministic", RetVoid, [ArgBufRWz, ArgVal, ArgBufRWz])
  , ("randombytes_close", RetVal, [])
  , ("randombytes", RetVoid, [ArgBufRWz, ArgI64])
  , ("randombytes_implementation_name", RetStr, [])
  , ("randombytes_random", RetVal, [])
  , ("randombytes_stir", RetVoid, [])
  , ("randombytes_uniform", RetVal, [ArgVal])

  , ("sodium_init", RetVal, [])

  , ("sodium_add", RetVoid, [ArgBufRWz, ArgBufRWz, ArgVal])
  , ("sodium_compare", RetVal, [ArgBufRWz, ArgBufRWz, ArgVal])
  , ("sodium_increment", RetVoid, [ArgBufRWz, ArgVal])
  , ("sodium_is_zero", RetVal, [ArgBufRWz, ArgVal])
  , ("sodium_pad", RetVal, [ArgBufRWz, ArgBufRWz, ArgVal, ArgVal, ArgVal])
  , ("sodium_sub", RetVoid, [ArgBufRWz, ArgBufRWz, ArgVal])
  , ("sodium_unpad", RetVal, [ArgBufRWz, ArgBufRWz, ArgVal, ArgVal])
  , ("sodium_memzero", RetVoid, [ArgBufWz, ArgVal])
  , ("sodium_memcmp", RetVal, [ArgBufRz, ArgBufRz, ArgVal])

  , ("sodium_base64_encoded_len", RetVal, [ArgVal, ArgVal])
  , ("sodium_bin2base64", RetStr, [ArgBufRWz, ArgVal, ArgBufRWz, ArgVal, ArgVal])
  , ("sodium_bin2hex", RetStr, [ArgBufRWz, ArgVal, ArgBufRWz, ArgVal])

  -- These don't support their pointer-to-pointer parameters, and expect a NULL pointer there.
  , ("sodium_base642bin", RetVal, [ArgBufRWz, ArgVal, ArgBufRWz, ArgVal, ArgBufRWz, ArgBufRWz, ArgPtrNull, ArgVal])
  , ("sodium_hex2bin", RetVal, [ArgBufRWz, ArgVal, ArgBufRWz, ArgVal, ArgBufRWz, ArgBufRWz, ArgPtrNull])
 ]

